### ISSUE TITLE
Suggestion: Change background color

### ISSUE THREAD

**Issue by JainamShah28** [jainam283/github-crash-course#1]
I think it looks better if the background color is red instead of orange.

The styling could be changed like this:

```css
body {
    background-color: red;
}
```
